@extends('admin.master')
@section('module_title')
  <link href="{{ asset('css/datepicker.css?ver=1.0')}}" rel="stylesheet"/>
  <script src="{{ asset('js/bootstrap-datepicker.js?ver=1.0')}}"></script>
  <section class="content-header">
    <h1> Course Payment </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Student Admission </li>
      <li class="active"> Course Payment </li>
    </ol>
  </section>
  <style type="text/css">
    .table > thead > tr > th,.table > tbody > tr > td,.table > tbody > tr > th {
        border-bottom: 2px solid black !important;
    }
  </style>
@stop
@section('admin_content')
  <div class="container">
    @if(Session::has('message'))
      <div class="alert alert-success" id="message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          {{ Session::get('message') }}
      </div>
    @endif
    @php
      $superSuperAdmin = 1;
      $superAdmin = 2;
      $subAdmin = 4;
    @endphp
    @if($superSuperAdmin == $loginUser->type || $superAdmin == $loginUser->type)
    <form action="{{url('admin/download-course-payments')}}" id="downloadForm">
      <div class="form-group row">
        <div class="col-sm-3">
          <input type="text" id="from" name="from" class="form-control" placeholder="yyyy-mm-dd">
        </div>
        <div class="col-sm-3">
          <input type="text" id="to" name="to" class="form-control" placeholder="yyyy-mm-dd" >
        </div>
        <div class="col-sm-2">
          <input type="button" name="Download" class="form-control btn btn-primary" value="Download" onClick="checkDate();">
        </div>
      </div>
      <div class="form-group row">
        <div class="col-sm-3">
          <select class="form-control" id="course" name="course" title="Course" onChange="selectSubCourse(this);">
            <option value="">Select Course</option>
            <option value="All">All</option>
            @if(count($courses) > 0)
              @foreach($courses as $course)
                  <option value="{{$course->id}}">{{$course->name}}</option>
              @endforeach
            @endif
          </select>
        </div>
        <div class="col-sm-3">
          <select class="form-control" id="subcourse" name="subcourse" title="Sub Course" onChange="selectBatch(this);">
            <option value="">Select Sub Course</option>
            <option value="All">All</option>
          </select>
        </div>
        <div class="col-sm-3">
          <select class="form-control" id="batch" name="batch" title="Batch" onChange="selectBatchUser(this);">
            <option value="">Select Batch</option>
            <option value="All">All</option>
          </select>
        </div>
        <div class="col-sm-3">
          <select class="form-control" id="user" name="user" onChange="showPayments();" title="User">
              <option value="">Select User</option>
              <option value="All">All</option>
          </select>
        </div>
      </div>
    </form>
    @endif
    <div style="overflow: auto; height: 600px;">
      <table class="table" border="1">
        <thead class="">
          <tr>
            <th>#</th>
            <th>UserId</th>
            <th>Course</th>
            <th>Sub Course</th>
            <th>Batch</th>
            <th>Admission</th>
            <th>Refund</th>
            <th>CGST</th>
            <th>SGST</th>
            <th>Total</th>
            <th>Date</th>
            @if($superAdmin == $loginUser->type || $superSuperAdmin == $loginUser->type)
              <th>Generated By</th>
            @endif
            <th>Comment</th>
            <th>Pdf</th>
            @if($superAdmin == $loginUser->type)
              <th>Delete</th>
            @endif
            @if($superSuperAdmin == $loginUser->type)
              <th>Toggle</th>
            @endif
          </tr>
        </thead>
        <tbody id="tbody">
          @php
            $admissionTotal = 0;
            $refundTotal = 0;
            $cgst = 0;
            $sgst = 0;
          @endphp
          @if(count($coursePayments) > 0)
            @foreach($coursePayments as $index => $coursePayment)
              <tr>
                <th>{{$index + 1}}</th>
                <td>
                  @if(1 == $coursePayment->course_payment_type)
                    <a href="{{url('admin/course-payment')}}/{{$coursePayment->id}}/edit">{{$coursePayment->user_id}}-{{$allUser[$coursePayment->user_id]}}</a>
                  @else
                    {{$coursePayment->user_id}}-{{$allUser[$coursePayment->user_id]}}
                  @endif
                </td>
                <td>{{$coursePayment->course->name}}</td>
                <td>{{$coursePayment->subcourse->name}}</td>
                <td>{{$coursePayment->batch->name}}</td>
                @if(1 == $coursePayment->fee_type)
                  @if(1 == $coursePayment->course_payment_type)
                    <td>{{round($coursePayment->amount/1.18,2)}}</td>
                    <td>0</td>
                    <td>+{{round(($coursePayment->amount/1.18) * 0.09,2)}}</td>
                    <td>+{{round(($coursePayment->amount/1.18) * 0.09,2)}}</td>
                  @else
                    <td>0</td>
                    <td>{{round($coursePayment->amount/1.18,2)}}</td>
                    <td>-{{round(($coursePayment->amount/1.18) * 0.09,2)}}</td>
                    <td>-{{round(($coursePayment->amount/1.18) * 0.09,2)}}</td>
                  @endif
                  @php
                    if(3 == $coursePayment->course_payment_type){
                      $refundTotal = $refundTotal + round($coursePayment->amount/1.18,2);
                      $cgst = $cgst - round(($coursePayment->amount/1.18) * 0.09,2);
                      $sgst = $sgst - round(($coursePayment->amount/1.18) * 0.09,2);
                    } elseif(1 == $coursePayment->course_payment_type){
                      $admissionTotal = $admissionTotal + round($coursePayment->amount/1.18,2);
                      $cgst = $cgst + round(($coursePayment->amount/1.18) * 0.09,2);
                      $sgst = $sgst + round(($coursePayment->amount/1.18) * 0.09,2);
                    }
                  @endphp
                @else
                  @if(1 == $coursePayment->course_payment_type)
                    <td>{{$coursePayment->amount}}</td>
                    <td>0</td>
                  @else
                    <td>0</td>
                    <td>{{$coursePayment->amount}}</td>
                  @endif
                  <td>0</td>
                  <td>0</td>
                  @php
                    if(3 == $coursePayment->course_payment_type){
                      $refundTotal = $refundTotal + $coursePayment->amount;
                      $cgst = $cgst - 0;
                      $sgst = $sgst - 0;
                    } elseif(1 == $coursePayment->course_payment_type){
                      $admissionTotal = $admissionTotal + $coursePayment->amount;
                      $cgst = $cgst + 0;
                      $sgst = $sgst + 0;
                    }
                  @endphp
                @endif
                <td>{{$coursePayment->amount}}</td>
                <td>{{$coursePayment->payment_date}}</td>
                @if($superAdmin == $loginUser->type || $superSuperAdmin == $loginUser->type)
                  <td>{{$coursePayment->admin->name}}</td>
                @endif
                <td>{{$coursePayment->comment}}</td>
                <td><a href="{{url('admin/show-student-receipt')}}/{{$coursePayment->id}}" target="_blank">view pdf</a></td>
                @if($superAdmin == $loginUser->type)
                <td>
                  <a id="{{$coursePayment->id}}" onclick="confirmDelete(this);"><img src="{{asset('images/delete2.png')}}" width='30' height='30' title="Delete" />
                      </a>
                      <form id="deleteCoursePayment_{{$coursePayment->id}}" action="{{url('admin/delete-course-payment')}}" method="POST" style="display: none;">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <input type="hidden" name="course_payment_id" value="{{$coursePayment->id}}">
                      </form>
                </td>
                @endif
                @if($superSuperAdmin == $loginUser->type)
                <td><input type="checkbox" name="{{$coursePayment->id}}" id="{{$coursePayment->id}}" onClick="toggleRecord(this);" @if(1 == $coursePayment->allow_to_visible) checked="true" @endif></td>
                @endif
              </tr>
            @endforeach
            <tr>
                <th colspan="4"></th>
                <td><b>Total:</b></td>
                <td>+{{$admissionTotal}}</td>
                <td>-{{$refundTotal}}</td>
                <td>+{{$cgst}}</td>
                <td>+{{$sgst}}</td>
                <td>{{($admissionTotal - $refundTotal + $cgst + $sgst)}}</td>
                <th colspan="5"></th>
              </tr>
          @endif
        </tbody>
      </table>
    </div>
    <input type="hidden" id="type" value="{{$loginUser->type}}">
</div>
<script type="text/javascript">
  $(function () {
    $("#from").datepicker({
          format: 'yyyy-mm-dd',
          autoclose: true,
          todayHighlight: true
    });
    $("#to").datepicker({
          format: 'yyyy-mm-dd',
          autoclose: true,
          todayHighlight: true
    }).on('changeDate', function(ev){
      var fromDate = document.getElementById('from').value;
      var toDate = document.getElementById('to').value;
      if(new Date(fromDate) > new Date(toDate)){
        $.alert({
          title: 'Alert',
          content: 'from date should be less than or equal to to date.',
        });
      } else {
        if(fromDate && toDate){
          $.ajax({
            method: "POST",
            url: "{{url('admin/get-user-total-paid-by-course-id-by-sub-course-id-by-batch-id-for-payments')}}",
            data: {from_date:fromDate,to_date:toDate}
          })
          .done(function( result ) {
            renderResult(result);
          });
        }
      }
    });
  });

  function toggleRecord(ele){
    var paymentId = $(ele).prop('id');
    $.ajax({
      method: "POST",
      url: "{{url('admin/toggle-records')}}",
      data: {course_payment_id:paymentId}
    })
    .done(function( msg ) {
      if('false' == msg){
        if('checked' == $(ele).attr('checked')){
          $(ele).prop('checked', 'checked');
        } else {
          $(ele).prop('checked', '');
        }
      }
      window.location.reload();
    });
  }

  function checkDate(){
    var fromDate = document.getElementById('from').value;
    var toDate = document.getElementById('to').value;
    if(new Date(fromDate) > new Date(toDate)){
      $.alert({
        title: 'Alert',
        content: 'from date should be less than or equal to to date.',
      });
    } else {
      document.getElementById('downloadForm').submit();
    }
  }

  function confirmDelete(ele){
    $.confirm({
      title: 'Confirmation',
      content: 'You want to delete this payment?',
      type: 'red',
      typeAnimated: true,
      buttons: {
        Ok: {
            text: 'Ok',
            btnClass: 'btn-red',
            action: function(){
              var id = $(ele).attr('id');
              formId = 'deleteCoursePayment_'+id;
              document.getElementById(formId).submit();
            }
        },
        Cancle: function () {
        }
      }
    });
  }

  function selectSubCourse(ele){
    var id = parseInt($(ele).val());
    if( 0 < id ){
      $.ajax({
          method: "POST",
          url: "{{url('admin/get-sub-courses-by-id')}}",
          data: {course_id:id}
      })
      .done(function( msg ) {
        select = document.getElementById('subcourse');
        select.innerHTML = '';
        var opt = document.createElement('option');
        opt.value = '';
        opt.innerHTML = 'Select Sub Course';
        select.appendChild(opt);
        var allOpt = document.createElement('option');
        allOpt.value = 'All';
        allOpt.innerHTML = 'All';
        select.appendChild(allOpt);
        if( 0 < msg.length){
          $.each(msg, function(idx, obj) {
              var opt = document.createElement('option');
              opt.value = obj.id;
              opt.innerHTML = obj.name;
              select.appendChild(opt);
          });
        }
      });
    } else {
      select = document.getElementById('subcourse');
      select.innerHTML = '';
      var opt = document.createElement('option');
      opt.value = '';
      opt.innerHTML = 'Select Sub Course';
      select.appendChild(opt);
      var allOpt = document.createElement('option');
      allOpt.value = 'All';
      allOpt.innerHTML = 'All';
      select.appendChild(allOpt);
    }
    defaultBatch()
    defaultUser();
  }

  function selectBatch(ele){
    var subCourseId = parseInt($(ele).val());
    var courseId = document.getElementById('course').value;
    if( subCourseId > 0 && courseId > 0 ){
      $.ajax({
          method: "POST",
          url: "{{url('admin/get-batches-by-course-id-by-sub-course-id')}}",
          data: {course_id:courseId,subcourse_id:subCourseId}
      })
      .done(function( msg ) {
        select = document.getElementById('batch');
        select.innerHTML = '';
        var opt = document.createElement('option');
        opt.value = '';
        opt.innerHTML = 'Select Batch';
        select.appendChild(opt);
        var allOpt = document.createElement('option');
        allOpt.value = 'All';
        allOpt.innerHTML = 'All';
        select.appendChild(allOpt);
        if( 0 < msg.length){
          $.each(msg, function(idx, obj) {
              var opt = document.createElement('option');
              opt.value = obj.id;
              opt.innerHTML = obj.name;
              select.appendChild(opt);
          });
        }
      });
    } else {
      defaultBatch()
    }
    defaultUser();
  }

  function selectBatchUser(ele){
    var batchId = parseInt($(ele).val());
    var courseId = document.getElementById('course').value;
    var subcourseId = document.getElementById('subcourse').value;
    if( subcourseId > 0 && courseId > 0 && batchId > 0){
      $.ajax({
          method: "POST",
          url: "{{url('admin/get-users-by-course-id-by-sub-course-id-by-batch-id')}}",
          data: {course_id:courseId,subcourse_id:subcourseId,batch_id:batchId}
      })
      .done(function( msg ) {
        select = document.getElementById('user');
        select.innerHTML = '';
        var opt = document.createElement('option');
        opt.value = '';
        opt.innerHTML = 'Select User';
        select.appendChild(opt);
        var allOpt = document.createElement('option');
        allOpt.value = 'All';
        allOpt.innerHTML = 'All';
        select.appendChild(allOpt);
        if( 0 < msg.length){
          $.each(msg, function(idx, obj) {
              var opt = document.createElement('option');
              opt.value = obj.id;
              opt.innerHTML = obj.f_name+' '+obj.l_name;
              select.appendChild(opt);
          });
        }
      });
    } else {
      defaultUser();
    }
  }

  function showPayments(){
    var userId = document.getElementById('user').value;
    var batchId = document.getElementById('batch').value;
    var courseId = document.getElementById('course').value;
    var subcourseId = document.getElementById('subcourse').value;
    var fromDate = document.getElementById('from').value;
    var toDate = document.getElementById('to').value;
    if(subcourseId && courseId && batchId && userId){
      $.ajax({
        method: "POST",
        url: "{{url('admin/get-user-total-paid-by-course-id-by-sub-course-id-by-batch-id-for-payments')}}",
        data: {course_id:courseId,subcourse_id:subcourseId,batch_id:batchId,user_id:userId,from_date:fromDate,to_date:toDate}
      })
      .done(function( result ) {
        renderResult(result);
      });
    }
  }

  function renderResult(result){
    body = document.getElementById('tbody');
    body.innerHTML = '';
    var index = 1;
    var admissionTotal = 0;
    var refundTotal = 0;
    var cgst = 0;
    var sgst = 0;
    if( 0 < result.length){
      $.each(result, function(idx, obj) {
          var eleTr = document.createElement('tr');
          var eleIndex = document.createElement('td');
          eleIndex.innerHTML = index++;
          eleTr.appendChild(eleIndex);

          var eleUserId = document.createElement('td');
          var editUrl = "{{url('admin/course-payment')}}/"+obj.id+'/edit';
          if(1 == obj.course_payment_type){
            eleUserId.innerHTML = '<a href="'+editUrl+'">'+obj.user_id+'-'+obj.name+'</a>' ;
          } else {
            eleUserId.innerHTML = obj.user_id+'-'+obj.name;
          }
          eleTr.appendChild(eleUserId);

          var eleCourse = document.createElement('td');
          eleCourse.innerHTML = obj.course;
          eleTr.appendChild(eleCourse);

          var eleSubCourse = document.createElement('td');
          eleSubCourse.innerHTML = obj.subcourse;
          eleTr.appendChild(eleSubCourse);

          var eleBatch = document.createElement('td');
          eleBatch.innerHTML = obj.batch;
          eleTr.appendChild(eleBatch);

          if(1 == obj.fee_type){
            var calAmount = obj.amount/1.18;
            if(1 == obj.course_payment_type){
              admissionTotal = parseFloat(admissionTotal) + parseFloat(calAmount.toFixed(2));
            } else {
              refundTotal = parseFloat(refundTotal) + parseFloat(calAmount.toFixed(2));
            }

            if(1 == obj.course_payment_type){
              var eleAdmission = document.createElement('td');
              eleAdmission.innerHTML = calAmount.toFixed(2);
              eleTr.appendChild(eleAdmission);

              var eleRefund = document.createElement('td');
              eleRefund.innerHTML = 0;
              eleTr.appendChild(eleRefund);

              var eleCgst = document.createElement('td');
              var calCgst = (obj.amount/1.18)*0.09;
              eleCgst.innerHTML = '+'+calCgst.toFixed(2);
              eleTr.appendChild(eleCgst);
              cgst = parseFloat(cgst) + parseFloat(calCgst.toFixed(2));

              var eleSgst = document.createElement('td');
              var calSgst = (obj.amount/1.18)*0.09;
              eleSgst.innerHTML = '+'+calSgst.toFixed(2);
              eleTr.appendChild(eleSgst);
              sgst = parseFloat(sgst) + parseFloat(calSgst.toFixed(2));
            } else {
              var eleAdmission = document.createElement('td');
              eleAdmission.innerHTML = 0;
              eleTr.appendChild(eleAdmission);

              var eleRefund = document.createElement('td');
              eleRefund.innerHTML = calAmount.toFixed(2);
              eleTr.appendChild(eleRefund);

              var eleCgst = document.createElement('td');
              var calCgst = (obj.amount/1.18)*0.09;
              eleCgst.innerHTML = '-'+calCgst.toFixed(2);
              eleTr.appendChild(eleCgst);
              cgst = parseFloat(cgst) - parseFloat(calCgst.toFixed(2));

              var eleSgst = document.createElement('td');
              var calSgst = (obj.amount/1.18)*0.09;
              eleSgst.innerHTML = '-'+calSgst.toFixed(2);
              eleTr.appendChild(eleSgst);
              sgst = parseFloat(sgst) - parseFloat(calSgst.toFixed(2));
            }
          } else {
            if(1 == obj.course_payment_type){
              var eleAdmission = document.createElement('td');
              eleAdmission.innerHTML = obj.amount;
              eleTr.appendChild(eleAdmission);
              admissionTotal = parseFloat(admissionTotal) + parseFloat(obj.amount);

              var eleRefund = document.createElement('td');
              eleRefund.innerHTML = 0;
              eleTr.appendChild(eleRefund);
            } else {
              var eleAdmission = document.createElement('td');
              eleAdmission.innerHTML = 0;
              eleTr.appendChild(eleAdmission);

              var eleRefund = document.createElement('td');
              eleRefund.innerHTML = obj.amount;
              eleTr.appendChild(eleRefund);
              refundTotal = parseFloat(refundTotal) + parseFloat(obj.amount);
            }
            var eleCgst = document.createElement('td');
            eleCgst.innerHTML = 0;
            eleTr.appendChild(eleCgst);
            cgst = parseFloat(cgst) + 0;

            var eleSgst = document.createElement('td');
            eleSgst.innerHTML = 0;
            eleTr.appendChild(eleSgst);
            sgst = parseFloat(sgst) + 0;
          }
          var eleAmount = document.createElement('td');
          eleAmount.innerHTML = parseFloat(obj.amount);
          eleTr.appendChild(eleAmount);

          var eleDate = document.createElement('td');
          eleDate.innerHTML = obj.created_at;
          eleTr.appendChild(eleDate);

          var eleAdmin = document.createElement('td');
          eleAdmin.innerHTML = obj.generated_by;
          eleTr.appendChild(eleAdmin);

          var eleComment = document.createElement('td');
          eleComment.innerHTML = obj.comment;
          eleTr.appendChild(eleComment);

          var elePdf = document.createElement('td');
          var pdfUrl = "{{url('admin/show-student-receipt')}}/"+obj.id;
          elePdf.innerHTML = '<a href="'+pdfUrl+'" target="_blank">view pdf</a>';
          eleTr.appendChild(elePdf);

          if(2 == $('#type').val()){
            var eleDelete = document.createElement('td');
            var deleteUrl = "{{url('admin/delete-course-payment')}}";
            var imageUrl  = "{{asset('images/delete2.png')}}";
            var csrfField = '{{ csrf_field() }}';
            var methodField = '{{ method_field('DELETE') }}';
            eleDelete.innerHTML = '<a id="'+obj.id+'" onclick="confirmDelete(this);"><img src="'+imageUrl+'" width="30" height="30" title="Delete" /></a><form id="deleteCoursePayment_'+obj.id+'" action="'+deleteUrl+'" method="POST" style="display: none;">'+csrfField+''+methodField+'<input type="hidden" name="course_payment_id" value="'+obj.id+'"></form>';
            eleTr.appendChild(eleDelete);
          }
          if(1 == $('#type').val()){
            var eleToggle = document.createElement('td');
            if(1 == obj.allow_to_visible){
              eleToggle.innerHTML = '<input type="checkbox" name="'+obj.id+'" id="'+obj.id+'" onClick="toggleRecord(this);" checked="true">';
            } else {
              eleToggle.innerHTML = '<input type="checkbox" name="'+obj.id+'" id="'+obj.id+'" onClick="toggleRecord(this);">';
            }
            eleTr.appendChild(eleToggle);
          }
          body.appendChild(eleTr);
      });
      var eleTr = document.createElement('tr');
      var eleIndex = document.createElement('td');
      eleIndex.innerHTML = '';
      eleIndex.setAttribute('colspan', '4');
      eleTr.appendChild(eleIndex);

      var eleTotal = document.createElement('td');
      eleTotal.innerHTML = '<b>Total:</b>';
      eleTr.appendChild(eleTotal);

      var eleAdmissionAmount = document.createElement('td');
      eleAdmissionAmount.innerHTML = '+'+admissionTotal.toFixed(2);
      eleTr.appendChild(eleAdmissionAmount);

      var eleRefundAmount = document.createElement('td');
      eleRefundAmount.innerHTML = '-'+refundTotal.toFixed(2);
      eleTr.appendChild(eleRefundAmount);

      var eleCgst = document.createElement('td');
      eleCgst.innerHTML = '+'+cgst.toFixed(2);
      eleTr.appendChild(eleCgst);

      var eleSgst = document.createElement('td');
      eleSgst.innerHTML = '+'+sgst.toFixed(2);
      eleTr.appendChild(eleSgst);

      var eleAmount = document.createElement('td');
      eleAmount.innerHTML = Math.round(admissionTotal - refundTotal + cgst + sgst);
      eleTr.appendChild(eleAmount);

      var eleStatus = document.createElement('td');
      eleStatus.innerHTML = '';
      eleStatus.setAttribute('colspan', '5');
      eleTr.appendChild(eleStatus);
      body.appendChild(eleTr);
    } else {
      var eleTr = document.createElement('tr');
      var eleIndex = document.createElement('td');
      eleIndex.innerHTML = 'No Result';
      eleIndex.setAttribute('colspan', '15');
      eleTr.appendChild(eleIndex);
      body.appendChild(eleTr);
    }
  }

  function defaultUser(){
    select = document.getElementById('user');
    select.innerHTML = '';
    var opt = document.createElement('option');
    opt.value = '';
    opt.innerHTML = 'Select User';
    select.appendChild(opt);
    var allOpt = document.createElement('option');
    allOpt.value = 'All';
    allOpt.innerHTML = 'All';
    select.appendChild(allOpt);
  }
  function defaultBatch(){
    select = document.getElementById('batch');
    select.innerHTML = '';
    var opt = document.createElement('option');
    opt.value = '';
    opt.innerHTML = 'Select Batch';
    select.appendChild(opt);
    var allOpt = document.createElement('option');
    allOpt.value = 'All';
    allOpt.innerHTML = 'All';
    select.appendChild(allOpt);
  }
</script>
@stop
