@extends('admin.master')
@section('module_title')
  <section class="content-header">
    <h1>Refund Formation </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-dashboard"></i> Student Admission </li>
      <li class="active">Refund Formation </li>
    </ol>
  </section>
@stop
@section('admin_content')
  &nbsp;
  <div class="container">
  @if(Session::has('message'))
    <div class="alert alert-success" id="message">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ Session::get('message') }}
    </div>
  @endif
  @if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
  @endif
    <div class="form-group row">
      <div id="">
        <a id="" href="{{url('admin/create-refund')}}" type="button" class="btn btn-primary" style="float: right;" title="Add Refund">Add Refund</a>&nbsp;&nbsp;
      </div>
    </div>
  @php
    $superSuperAdmin = 1;
    $superAdmin = 2;
    $admin = 3;
    $subAdmin = 4;
  @endphp
  <div style="overflow: auto;">
    <table class="table admin_table">
      <thead class="thead-inverse">
        <tr>
          <th>#</th>
          <th>User Id</th>
          <th>Batch</th>
          <th>Sub Course</th>
          <th>Course</th>
          <th>Refund</th>
          @if($superSuperAdmin == $loginUser->type || $superAdmin == $loginUser->type)
            <th>Generated By</th>
          @endif
          <th>Edit</th>
          @if($superAdmin == $loginUser->type)
            <th>Delete</th>
          @endif
        </tr>
      </thead>
      <tbody>
        @if(count($coursePayments) > 0)
          @foreach($coursePayments as $index => $coursePayment)
          <tr>
            <th scope="row">{{$index + 1}}</th>
            <td>{{$coursePayment->user_id}}</td>
            <td>{{$coursePayment->batch->name}}</td>
            <td>{{$coursePayment->subcourse->name}}</td>
            <td>{{$coursePayment->course->name}}</td>
            <td>{{$coursePayment->amount}}</td>
            @if($superSuperAdmin == $loginUser->type || $superAdmin == $loginUser->type)
              <td>{{$coursePayment->admin->name}}</td>
            @endif
            <td>
              <a href="{{url('admin/refund')}}/{{$coursePayment->id}}/edit" ><img src="{{asset('images/edit1.png')}}" width='30' height='30'/>
                </a>
            </td>
            @if($superAdmin == $loginUser->type)
            <td>
              <a id="{{$coursePayment->id}}" onclick="confirmDelete(this);"><img src="{{asset('images/delete2.png')}}" width='30' height='30'/>
              </a>
              <form id="deleteDiscount_{{$coursePayment->id}}" action="{{url('admin/delete-refund')}}" method="POST" style="display: none;">
                  {{ csrf_field() }}
                  {{ method_field('DELETE') }}
                  <input type="hidden" name="course_payment_id" value="{{$coursePayment->id}}">
              </form>
            </td>
            @endif
          </tr>
          @endforeach
        @else
          <tr><td colspan="8">No refund is created.</td></tr>
        @endif
      </tbody>
    </table>
  </div>
  </div>
<script type="text/javascript">
    function confirmDelete(ele){
      $.confirm({
        title: 'Confirmation',
        content: 'Are you sure, you want to delete this refund',
        type: 'red',
        typeAnimated: true,
        buttons: {
              Ok: {
                  text: 'Ok',
                  btnClass: 'btn-red',
                  action: function(){
                    var id = $(ele).attr('id');
                    formId = 'deleteDiscount_'+id;
                    document.getElementById(formId).submit();
                  }
              },
              Cancle: function () {
              }
          }
        });
    }
</script>
@stop